// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bangladesh",
                            ShortName = "BD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "India",
                            ShortName = "IN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "America",
                            ShortName = "USA"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Gulshan",
                            CountryId = 1,
                            Name = "Get Better",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Banani",
                            CountryId = 1,
                            Name = "Sun Shine",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Las Vegas",
                            CountryId = 3,
                            Name = "Disco",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mumbai",
                            CountryId = 2,
                            Name = "Butterfly",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Address = "Uttara",
                            CountryId = 1,
                            Name = "Rising Up",
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
