// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeStore.Models;

namespace TreeStore.Migrations
{
    [DbContext(typeof(TreeDbContext))]
    [Migration("20210308163723_AddedTypeToDb")]
    partial class AddedTypeToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreeStore.Models.Tree", b =>
                {
                    b.Property<int>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("TreeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Trees");

                    b.HasData(
                        new
                        {
                            TreeId = 1,
                            Name = "Mango Tree",
                            Rating = 4,
                            TypeId = 1,
                            Year = 2001
                        },
                        new
                        {
                            TreeId = 2,
                            Name = "Cocunut Tree",
                            Rating = 3,
                            TypeId = 2,
                            Year = 2010
                        },
                        new
                        {
                            TreeId = 3,
                            Name = "Banyan Tree",
                            Rating = 5,
                            TypeId = 3,
                            Year = 2020
                        },
                        new
                        {
                            TreeId = 4,
                            Name = "Berry Tree",
                            Rating = 3,
                            TypeId = 2,
                            Year = 2015
                        },
                        new
                        {
                            TreeId = 5,
                            Name = "Jackfruit Tree",
                            Rating = 5,
                            TypeId = 2,
                            Year = 2010
                        });
                });

            modelBuilder.Entity("TreeStore.Models.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Name = "Summer"
                        },
                        new
                        {
                            TypeId = 2,
                            Name = "Winter"
                        },
                        new
                        {
                            TypeId = 3,
                            Name = "Spring"
                        },
                        new
                        {
                            TypeId = 4,
                            Name = "Rainy"
                        },
                        new
                        {
                            TypeId = 5,
                            Name = "All Season"
                        });
                });

            modelBuilder.Entity("TreeStore.Models.Tree", b =>
                {
                    b.HasOne("TreeStore.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
